feat: add BTC to ramp currency list
brave/token-lists pull request #106
Opened 2023-12-21 13:15 UTC by josheleonard

Adds Bitcoin to purchasable and sellable assets list

2023-12-21 21:48 UTC, Douglashdaniel approved these changes
++

2023-12-22 13:24 UTC, onyb requested changes
Please bump the patch version in `package.json`

2023-12-22 13:28 UTC, josheleonard commented
@onyb, version has now been bumped

2023-12-22 13:29 UTC, onyb approved these changes
++

2023-12-22 13:49 UTC, merged